version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend_nw

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
    healthcheck:
      test: python3 -c 'import http.client;http.client.HTTPConnection("127.0.0.1:9000", timeout=1).request("GET", "/ping/")'
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - backend_nw
      - frontend_nw
    volumes:
#      - ./todolist:/project/todolist
#      - ./core:/project/core
#      - ./goals:/project/goals
      - ./static:/project/static

  frontend:
    image: doom2/tick-tick-frontend:v3.2
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - frontend_nw
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static/

volumes:
  pg_data:
  static:

networks:
  backend_nw:
    driver: bridge
  frontend_nw:
    driver: bridge
