version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_nw
      - bot_nw

  api:
    image: doom2/tick-tick:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: python3 -c 'import http.client;http.client.HTTPConnection("api:9000", timeout=1).request("GET", "/ping/")'  || exit 1
      interval: 3s
      timeout: 3s
      retries: 5

    volumes:
      - ./static:/project/static
    networks:
      - backend_nw
      - frontend_nw

  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "81:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static/
    networks:
      - frontend_nw

  bot:
    image: doom2/tick-tick-tg-bot:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

    networks:
      - bot_nw

volumes:
  pg_data:

networks:
  backend_nw:
    driver: bridge
  frontend_nw:
    driver: bridge
  bot_nw:
    driver: bridge
