# Generated by Django 4.1.4 on 2023-01-23 11:10
from django.apps.registry import Apps
from django.db import migrations, transaction
from django.db.models import Model
from django.utils import timezone


def create_objects(apps: Apps, schema_editor):
    User: Model = apps.get_model('core', 'User')
    Board: Model = apps.get_model('goals', 'Board')
    BoardParticipant: Model = apps.get_model('goals', 'BoardParticipant')
    GoalCategory: Model = apps.get_model('goals', 'GoalCategory')

    with transaction.atomic():  # apply all changes with one transaction
        now = timezone.now()
        for user in User.objects.all():
            new_board = Board.objects.create(
                title='My goals',
                created=now,
                updated=now
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=now,
                updated=now
            )

            # apply to all user categories his board
            GoalCategory.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0002_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
