# Generated by Django 4.1.4 on 2023-02-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('tg_chat_id', models.PositiveIntegerField(verbose_name='tg chat')),
                ('tg_user_id', models.PositiveIntegerField(verbose_name='tg user')),
                ('verification_code', models.CharField(max_length=20, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'TgUser',
                'verbose_name_plural': 'TgUsers',
            },
        ),
    ]
